### Business background
- Ride-hailing companies - China's Didi
- You are a new risk management analyst in the financial business
- The leader hears that fortune-telling apps are making a lot of money. Then he wants to know whether it is feasible to make money from metaphysics and asks you to issue an analysis report

### To import  libraries relating to data analysis

In [2]:
import pandas as pd
import numpy as np
import copy

### To import data

In [3]:
f=open(r"ft_zodiac1.txt",encoding="utf-8")
ft_zodiac=pd.read_csv(f)

In [4]:
print(ft_zodiac.shape)

(23519, 4)

In [5]:
ft_zodiac.head()

   0            order_id chinese_zodiac       zodiac
0  0  100000081567592448            dog        Virgo
1  0  100000467565182976             ox       Gemini
2  0  100000530945323008          sheep  Sagittarius
3  0  100000556765458432            rat    Capricorn
4  0  100000598171623424          tiger     Aquarius

In [6]:
len(set(ft_zodiac.chinese_zodiac))

12

### Univariate analysis
- Whether this variable has a significant impact on our process and results
- badrate=bad/total

In [7]:
l=open(r"zodiac_label.txt",encoding="utf-8")
zodiac_label=pd.read_csv(l)
set(zodiac_label.label)# 只有三种标签 0 逾期5天内 1-预期15天以上 2-中甲

{0, 1, 2}

In [8]:
ft_label=zodiac_label[zodiac_label["label"]!=2]# 
ft_label.shape
ft_label

                 order_id  overdue_days  repay_time  label
0      100000081567592448             0  2018-07-09      0
1      100000467565182976             1  2018-07-09      0
2      100000530945323008             0  2018-07-09      0
3      100000556765458432             0  2018-07-09      0
4      100000598171623424             0  2018-07-09      0
5      100000839541235712            17  2018-07-09      1
6      100001014112362496             0  2018-07-09      0
7      100001026275844096             0  2018-07-09      0
8      100001059033362432             0  2018-07-09      0
9      100001069510721536             2  2018-07-09      0
10     100001236284649472             0  2018-07-09      0
11     100001301317320704             0  2018-07-09      0
12     100002022041362432             0  2018-07-09      0
13     100002027296825344            17  2018-07-09      1
14     100002132565467136             0  2018-07-09      0
15     100002202291568640            17  2018-07-09      1
16     100002254749728768             1  2018-07-09      0
17     100002266212761600             0  2018-07-09      0
18     100002319505600512             0  2018-07-09      0
19     100002338002477056             0  2018-07-09      0
20     100002474808082432             0  2018-07-09      0
21     100002512871399424             0  2018-07-09      0
22     100002683256614912             0  2018-07-09      0
23     100002946805694464            17  2018-07-09      1
24     100002976614625280             1  2018-07-09      0
25     100003084185939968             1  2018-07-09      0
26     100003246492917760             0  2018-07-09      0
27     100003543801966592             1  2018-07-09      0
28     100003608901754880            17  2018-07-09      1
29     100003624307433472             0  2018-07-09      0
...                   ...           ...         ...    ...
43402   99995733538152448             0  2018-07-09      0
43403   99995777939058688             1  2018-07-09      0
43404   99995979492130816             1  2018-07-09      0
43405   99996229225193472             0  2018-07-09      0
43406   99996371500183552             0  2018-07-09      0
43407   99996423434043392             0  2018-07-09      0
43408   99996521110994944             0  2018-07-09      0
43409   99996636114616320             1  2018-07-09      0
43410   99996734974373888             0  2018-07-09      0
43411   99996926490484736             0  2018-07-09      0
43412   99996985001025536            17  2018-07-09      1
43413   99997023286636544             0  2018-07-09      0
43414   99997107227230208             0  2018-07-09      0
43415   99997255093223424             0  2018-07-09      0
43416   99997392771260416             1  2018-07-09      0
43417   99997674238423040             0  2018-07-09      0
43418   99997814407868416             0  2018-07-09      0
43419   99997908679032832            17  2018-07-09      1
43420   99997936046874624             0  2018-07-09      0
43421   99997964920467456             0  2018-07-09      0
43422   99998262833487872             1  2018-07-09      0
43423   99998264091783168             0  2018-07-09      0
43424   99998413497085952             0  2018-07-09      0
43425   99998427313111040             1  2018-07-09      0
43426   99998726513795072             0  2018-07-09      0
43427   99998779156508672             0  2018-07-09      0
43428   99999561134153728             0  2018-07-09      0
43429   99999826155438080             0  2018-07-09      0
43430   99999845814153216             0  2018-07-09      0
43431   99999993764032512             0  2018-07-09      0

[42892 rows x 4 columns]

In [9]:
data=pd.merge(ft_label,ft_zodiac,how="inner",on="order_id")
data.head()

,order_id,overdue_days,repay_time,label,0,chinese_zodiac,zodiac
0,100000081567592448,0,2018-07-09,0,0,dog,Virgo
1,100000467565182976,1,2018-07-09,0,0,ox,Gemini
2,100000530945323008,0,2018-07-09,0,0,sheep,Sagittarius
3,100000556765458432,0,2018-07-09,0,0,rat,Capricorn
4,100000598171623424,0,2018-07-09,0,0,tiger,Aquarius

In [10]:
data.shape

(17117, 7)

In [11]:
zodiac_list=set(data.zodiac)
chinese_zodiac_list=set(data.chinese_zodiac)

#### To calculate badrate
- Constellation
- Chinese zodiac

##### Badrate of each constellation
- Store in a dictionary
- Sorted by badrate, and stored in the new dictionary

In [12]:
zodiac_badrate={}
for x in zodiac_list:
    a = data[data.zodiac == x]
    bad=a[a.label == 1]["label"].count()
    good=a[a.label == 0]["label"].count()
    zodiac_badrate[x]=bad/(bad+good)

In [13]:
zodiac_badrate

{'Taurus': 0.12259059367771781,
 'LEO': 0.12760416666666666,
 'Pisces': 0.14873646209386282,
 'Capricorn': 0.12920489296636087,
 'Gemini': 0.1312410841654779,
 'Aquarius': 0.140117994100295,
 'Sagittarius': 0.14480286738351256,
 'Virgo': 0.13035143769968052,
 'Cancri': 0.1408351026185421,
 'Aries': 0.13455414012738853,
 'Scorpius': 0.12005028284098052,
 'Libreast support': 0.12461252324860508}

In [15]:
f1 = zip(zodiac_badrate.keys(),zodiac_badrate.values())# 将原始统计的键名与值提出来
f1_list=copy.deepcopy(list(f1))
print(f1_list)
f2_list=sorted(f1_list,key= lambda x:x[1],reverse=True)
print(f2_list)

[('Taurus', 0.12259059367771781), ('LEO', 0.12760416666666666), ('Pisces', 0.14873646209386282), ('Capricorn', 0.12920489296636087), ('Gemini', 0.1312410841654779), ('Aquarius', 0.140117994100295), ('Sagittarius', 0.14480286738351256), ('Virgo', 0.13035143769968052), ('Cancri', 0.1408351026185421), ('Aries', 0.13455414012738853), ('Scorpius', 0.12005028284098052), ('Libreast support', 0.12461252324860508)]
[('Pisces', 0.14873646209386282), ('Sagittarius', 0.14480286738351256), ('Cancri', 0.1408351026185421), ('Aquarius', 0.140117994100295), ('Aries', 0.13455414012738853), ('Gemini', 0.1312410841654779), ('Virgo', 0.13035143769968052), ('Capricorn', 0.12920489296636087), ('LEO', 0.12760416666666666), ('Libreast support', 0.12461252324860508), ('Taurus', 0.12259059367771781), ('Scorpius', 0.12005028284098052)]

In [16]:
zodiac_badrate1=pd.DataFrame(f2_list)
zodiac_badrate1.columns=pd.Series(["constellation","badrate"])
zodiac_badrate1.head()

  constellation   badrate
0        Pisces  0.148736
1   Sagittarius  0.144803
2        Cancri  0.140835
3      Aquarius  0.140118
4         Aries  0.134554

In [17]:
from pyecharts.charts import Line
from pyecharts import options as opts

In [22]:
x = zodiac_badrate1["constellation"]
y = zodiac_badrate1["badrate"]
line1=(
    Line()
    .add_xaxis(list(x))
    .add_yaxis("badrate",list(y))
    .set_global_opts(title_opts=opts.TitleOpts(title='Univariate analysis'))
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
)

In [23]:
line1.render('pyecharts-line.html')

'C:\\Users\\zhangru\\0003.Ru Zhang\\Deep learning items\\Financial risk control and anti-fraud\\English\\2.Univariate analysis\\pyecharts-line.html'

In [24]:
line1.render_notebook()

In [21]:
from pyecharts.charts import Bar

In [29]:
x = zodiac_badrate1["constellation"]
y = zodiac_badrate1["badrate"]
Bar1=(
    Bar()
    .add_xaxis(list(x))
    .add_yaxis("badrate",list(y))
    .set_global_opts(title_opts=opts.TitleOpts(title='Univariate analysis'))
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
)

In [30]:
Bar1.render_notebook()

##### Badrate of each Chinese zodiac 
- Store in a dictionary
- Sorted by badrate, and stored in the new dictionary

In [31]:
data.head()

,order_id,overdue_days,repay_time,label,0,chinese_zodiac,zodiac
0,100000081567592448,0,2018-07-09,0,0,dog,Virgo
1,100000467565182976,1,2018-07-09,0,0,ox,Gemini
2,100000530945323008,0,2018-07-09,0,0,sheep,Sagittarius
3,100000556765458432,0,2018-07-09,0,0,rat,Capricorn
4,100000598171623424,0,2018-07-09,0,0,tiger,Aquarius

In [32]:
chinese_zodiac_list=set(data.chinese_zodiac)
chinese_zodiac_list

{'dog',
 'dragon',
 'horse',
 'monkey',
 'ox',
 'pig',
 'rabbit',
 'rat',
 'rooster',
 'sheep',
 'snake',
 'tiger'}

In [33]:
chinese_zodiac_badrate={}
for x in chinese_zodiac_list:
    a = data[data.chinese_zodiac== x]
    bad=a[a.label == 1]["label"].count()
    good=a[a.label == 0]["label"].count()
    chinese_zodiac_badrate[x]=bad/(bad+good)
chinese_zodiac_badrate

{'sheep': 0.11335403726708075,
 'horse': 0.12053872053872054,
 'pig': 0.14269406392694065,
 'dog': 0.11052009456264776,
 'rooster': 0.12846998063266624,
 'monkey': 0.12008141112618724,
 'tiger': 0.15165876777251186,
 'ox': 0.1578112609040444,
 'dragon': 0.1439084219133279,
 'snake': 0.12789827973074047,
 'rat': 0.1340602950609365,
 'rabbit': 0.1502843216896832}

In [34]:
v1 = zip(chinese_zodiac_badrate.keys(),chinese_zodiac_badrate.values())# 将原始统计的键名与值提出来
v1_list=copy.deepcopy(list(v1))
print(v1_list)

[('sheep', 0.11335403726708075), ('horse', 0.12053872053872054), ('pig', 0.14269406392694065), ('dog', 0.11052009456264776), ('rooster', 0.12846998063266624), ('monkey', 0.12008141112618724), ('tiger', 0.15165876777251186), ('ox', 0.1578112609040444), ('dragon', 0.1439084219133279), ('snake', 0.12789827973074047), ('rat', 0.1340602950609365), ('rabbit', 0.1502843216896832)]

In [35]:
v2_list=sorted(v1_list,key= lambda x:x[1],reverse=True)
print(v2_list)

[('ox', 0.1578112609040444), ('tiger', 0.15165876777251186), ('rabbit', 0.1502843216896832), ('dragon', 0.1439084219133279), ('pig', 0.14269406392694065), ('rat', 0.1340602950609365), ('rooster', 0.12846998063266624), ('snake', 0.12789827973074047), ('horse', 0.12053872053872054), ('monkey', 0.12008141112618724), ('sheep', 0.11335403726708075), ('dog', 0.11052009456264776)]

In [36]:
chinese_zodiac_badrate1=pd.DataFrame(v2_list)
chinese_zodiac_badrate1.columns=pd.Series(["Chinese zodiac","badrate"])
chinese_zodiac_badrate1.head()

  Chinese zodiac   badrate
0             ox  0.157811
1          tiger  0.151659
2         rabbit  0.150284
3         dragon  0.143908
4            pig  0.142694

In [40]:
s = chinese_zodiac_badrate1["Chinese zodiac"]
b = chinese_zodiac_badrate1["badrate"]
Bar1=(
    Bar()
    .add_xaxis(list(s))
    .add_yaxis("badrate",list(b))
    .set_global_opts(title_opts=opts.TitleOpts(title='Univariate analysis'))
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
)
line1=(
    Line()
    .add_xaxis(list(s))
    .add_yaxis("badrate",list(b))
    .set_global_opts(title_opts=opts.TitleOpts(title='Univariate analysis'))
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
)

In [41]:
Bar1.render_notebook()

In [42]:
line1.render_notebook()